import { createClient as createGeneratedBackendClient, SdkworkAppstoreBackendClient } from '../generated/server-openapi/src/index';
import type { SdkworkBackendConfig } from '../generated/server-openapi/src/types/common';
export { SdkworkAppstoreBackendClient, createGeneratedBackendClient };
export type { SdkworkBackendConfig };
export type SdkworkBackendClient = SdkworkAppstoreBackendClient;
export * from '../generated/server-openapi/src/types';
export * from '../generated/server-openapi/src/api';
export * from '../generated/server-openapi/src/http';
export * from '../generated/server-openapi/src/auth';
export const createClient = (config: SdkworkBackendConfig) => createGeneratedBackendClient(config);
