// @generated by tools/gen_appstore_http_route_manifest.py — do not edit

use sdkwork_web_core::{HttpMethod, HttpRoute, HttpRouteManifest};

const HTTP_ROUTES: &[HttpRoute] = &[
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/moderation/queue",
        "appstore",
        "appstore.moderation.queue.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/moderation/reviews/{reviewId}",
        "appstore",
        "appstore.moderation.reviews.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/moderation/reviews/{reviewId}/assign",
        "appstore",
        "appstore.moderation.reviews.assign",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/moderation/reviews/{reviewId}/decisions",
        "appstore",
        "appstore.moderation.decisions.create",
    ),
];

pub fn backend_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(HTTP_ROUTES)
}
