// @generated by tools/gen_appstore_http_route_manifest.py — do not edit

use sdkwork_web_core::{HttpMethod, HttpRoute, HttpRouteManifest};

const HTTP_ROUTES: &[HttpRoute] = &[
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/listings/{listingId}/compliance",
        "appstore",
        "appstore.compliance.profile.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Put,
        "/app/v3/api/listings/{listingId}/compliance",
        "appstore",
        "appstore.compliance.profile.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Put,
        "/app/v3/api/listings/{listingId}/compliance/permissions",
        "appstore",
        "appstore.compliance.permissions.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/listings/{listingId}/compliance/iap_items",
        "appstore",
        "appstore.compliance.iapItems.list",
    ),
];

pub fn app_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(HTTP_ROUTES)
}
