// @generated by tools/gen_appstore_http_route_manifest.py — do not edit

use sdkwork_web_core::{HttpMethod, HttpRoute, HttpRouteManifest};

const HTTP_ROUTES: &[HttpRoute] = &[
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/catalog/collections",
        "appstore",
        "appstore.catalog.collections.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/catalog/collections/{collectionId}",
        "appstore",
        "appstore.catalog.collections.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Put,
        "/backend/v3/api/catalog/collections/{collectionId}/items",
        "appstore",
        "appstore.catalog.collections.items.upsert",
    ),
    HttpRoute::dual_token(
        HttpMethod::Put,
        "/backend/v3/api/catalog/featured/{slotCode}",
        "appstore",
        "appstore.catalog.featured.upsert",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/catalog/categories",
        "appstore",
        "appstore.catalog.categories.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/catalog/categories/{categoryId}",
        "appstore",
        "appstore.catalog.categories.update",
    ),
];

pub fn backend_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(HTTP_ROUTES)
}
