// @generated by tools/gen_appstore_http_route_manifest.py — do not edit

use sdkwork_web_core::{HttpMethod, HttpRoute, HttpRouteManifest};

const HTTP_ROUTES: &[HttpRoute] = &[
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/listings/{listingId}/releases",
        "appstore",
        "appstore.releases.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/releases/{releaseId}",
        "appstore",
        "appstore.releases.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/app/v3/api/releases/{releaseId}",
        "appstore",
        "appstore.releases.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Put,
        "/app/v3/api/releases/{releaseId}/notes/{locale}",
        "appstore",
        "appstore.releases.notes.upsert",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/releases/{releaseId}/artifacts",
        "appstore",
        "appstore.releases.artifacts.attach",
    ),
    HttpRoute::dual_token(
        HttpMethod::Put,
        "/app/v3/api/releases/{releaseId}/rollout",
        "appstore",
        "appstore.releases.rollout.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/releases/{releaseId}/retire",
        "appstore",
        "appstore.releases.retire",
    ),
];

pub fn app_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(HTTP_ROUTES)
}
