// @generated by tools/gen_appstore_http_route_manifest.py — do not edit

use sdkwork_web_core::{HttpMethod, HttpRoute, HttpRouteManifest};

const HTTP_ROUTES: &[HttpRoute] = &[
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/listings/{listingId}",
        "appstore",
        "appstore.listings.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/listings/{listingId}/media",
        "appstore",
        "appstore.listings.media.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/listings/{listingId}/releases",
        "appstore",
        "appstore.listings.releases.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/listings",
        "appstore",
        "appstore.listings.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/app/v3/api/listings/{listingId}",
        "appstore",
        "appstore.listings.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Put,
        "/app/v3/api/listings/{listingId}/localizations/{locale}",
        "appstore",
        "appstore.listings.localization.upsert",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/listings/{listingId}/media",
        "appstore",
        "appstore.listings.media.attach",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/app/v3/api/listings/{listingId}/media/{mediaId}",
        "appstore",
        "appstore.listings.media.remove",
    ),
    HttpRoute::dual_token(
        HttpMethod::Put,
        "/app/v3/api/listings/{listingId}/categories",
        "appstore",
        "appstore.listings.categories.bind",
    ),
    HttpRoute::dual_token(
        HttpMethod::Put,
        "/app/v3/api/listings/{listingId}/regions",
        "appstore",
        "appstore.listings.regions.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/listings/{listingId}/submissions",
        "appstore",
        "appstore.listings.submissions.create",
    ),
];

pub fn app_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(HTTP_ROUTES)
}
