// @generated by tools/gen_appstore_http_route_manifest.py — do not edit

use sdkwork_web_core::{HttpMethod, HttpRoute, HttpRouteManifest};

const HTTP_ROUTES: &[HttpRoute] = &[
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/catalog/home",
        "appstore",
        "appstore.catalog.home.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/catalog/categories",
        "appstore",
        "appstore.catalog.categories.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/catalog/categories/{categoryId}",
        "appstore",
        "appstore.catalog.categories.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/catalog/collections",
        "appstore",
        "appstore.catalog.collections.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/catalog/collections/{collectionId}",
        "appstore",
        "appstore.catalog.collections.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/catalog/featured",
        "appstore",
        "appstore.catalog.featured.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/catalog/charts/{chartCode}",
        "appstore",
        "appstore.catalog.charts.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/catalog/listings/search",
        "appstore",
        "appstore.catalog.listings.search",
    ),
];

pub fn app_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(HTTP_ROUTES)
}
