// @generated by tools/gen_appstore_http_route_manifest.py — do not edit

use sdkwork_web_core::{HttpMethod, HttpRoute, HttpRouteManifest};

const HTTP_ROUTES: &[HttpRoute] = &[
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/market_channels",
        "appstore",
        "appstore.marketChannels.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/market_channels",
        "appstore",
        "appstore.marketChannels.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/market_channels/{marketChannelId}",
        "appstore",
        "appstore.marketChannels.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/market_releases",
        "appstore",
        "appstore.marketReleases.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/market_releases/{marketReleaseId}/sync",
        "appstore",
        "appstore.marketReleases.sync",
    ),
];

pub fn backend_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(HTTP_ROUTES)
}
