// @generated by tools/gen_appstore_http_route_manifest.py - do not edit

use sdkwork_web_core::{HttpMethod, HttpRoute, HttpRouteManifest};

const HTTP_ROUTES: &[HttpRoute] = &[
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/publishers/me",
        "appstore",
        "appstore.publishers.me.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/publishers/me/listings",
        "appstore",
        "appstore.publishers.me.listings.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/publishers/me/apps",
        "appstore",
        "appstore.publishers.me.apps.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/publishers",
        "appstore",
        "appstore.publishers.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/app/v3/api/publishers/{publisherId}",
        "appstore",
        "appstore.publishers.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/publishers/{publisherId}/members",
        "appstore",
        "appstore.publishers.members.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/publishers/{publisherId}/members",
        "appstore",
        "appstore.publishers.members.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/publishers/{publisherId}/verifications",
        "appstore",
        "appstore.publishers.verifications.create",
    ),
];

pub fn app_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(HTTP_ROUTES)
}
