// @generated by tools/gen_appstore_http_route_manifest.py — do not edit

use sdkwork_web_core::{HttpMethod, HttpRoute, HttpRouteManifest};

const HTTP_ROUTES: &[HttpRoute] = &[
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/metrics/listings/{listingId}",
        "appstore",
        "appstore.metrics.listings.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/analytics/publisher/overview",
        "appstore",
        "appstore.analytics.publisher.overview.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/analytics/publisher/listings",
        "appstore",
        "appstore.analytics.publisher.listings.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/analytics/publisher/listings/{listingId}",
        "appstore",
        "appstore.analytics.publisher.listings.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/analytics/operator/dashboard",
        "appstore",
        "appstore.analytics.operator.dashboard.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/analytics/operator/search",
        "appstore",
        "appstore.analytics.operator.search.retrieve",
    ),
];

pub fn backend_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(HTTP_ROUTES)
}
