// @generated by tools/gen_appstore_http_route_manifest.py — do not edit

use sdkwork_web_core::{HttpMethod, HttpRoute, HttpRouteManifest};

const HTTP_ROUTES: &[HttpRoute] = &[
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/listings",
        "appstore",
        "appstore.listings.admin.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/listings/{listingId}",
        "appstore",
        "appstore.listings.admin.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/listings/{listingId}/visibility",
        "appstore",
        "appstore.listings.admin.visibility.update",
    ),
];

pub fn backend_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(HTTP_ROUTES)
}
