// @generated by tools/gen_appstore_http_route_manifest.py - do not edit

use sdkwork_web_core::{HttpMethod, HttpRoute, HttpRouteManifest};

const HTTP_ROUTES: &[HttpRoute] = &[
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/library/items",
        "appstore",
        "appstore.library.items.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/library/items/{libraryItemId}",
        "appstore",
        "appstore.library.items.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/library/install",
        "appstore",
        "appstore.library.install",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/library/uninstall",
        "appstore",
        "appstore.library.uninstall",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/library/updates/check",
        "appstore",
        "appstore.library.updates.check",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/wishlist/items",
        "appstore",
        "appstore.wishlist.items.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/wishlist/items",
        "appstore",
        "appstore.wishlist.items.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/app/v3/api/wishlist/items/{listingId}",
        "appstore",
        "appstore.wishlist.items.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/download_grants",
        "appstore",
        "appstore.downloadGrants.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/download_grants/{grantId}/consume",
        "appstore",
        "appstore.downloadGrants.consume",
    ),
];

pub fn app_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(HTTP_ROUTES)
}
