#!/usr/bin/env python3
"""Generate combined appstore api-server http_route_manifest.rs."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

APP_CRATES = [
    "sdkwork-router-catalog-app-api",
    "sdkwork-router-compliance-app-api",
    "sdkwork-router-library-app-api",
    "sdkwork-router-publisher-app-api",
    "sdkwork-router-release-app-api",
    "sdkwork-router-listing-app-api",
]

BACKEND_CRATES = [
    "sdkwork-router-catalog-backend-api",
    "sdkwork-router-listing-backend-api",
    "sdkwork-router-publisher-backend-api",
    "sdkwork-router-moderation-backend-api",
    "sdkwork-router-market-backend-api",
    "sdkwork-router-metrics-backend-api",
]

OPEN_CRATES = [
    "sdkwork-router-catalog-open-api",
    "sdkwork-router-listing-open-api",
    "sdkwork-router-release-open-api",
    "sdkwork-router-automation-open-api",
]

ROUTE_ENTRY = re.compile(
    r"HttpRoute::(\w+)\(\s*"
    r"HttpMethod::(\w+),\s*"
    r'"([^"]+)",\s*'
    r'"([^"]+)",\s*'
    r'"([^"]+)",\s*'
    r"\),",
    re.MULTILINE,
)


def extract_http_routes(manifest_path: Path) -> list[str]:
    if not manifest_path.exists():
        return []
    text = manifest_path.read_text(encoding="utf-8")
    blocks: list[str] = []
    for auth, method, path, tag, op in ROUTE_ENTRY.findall(text):
        blocks.append(
            "\n".join(
                [
                    f"    HttpRoute::{auth}(",
                    f"        HttpMethod::{method},",
                    f'        "{path}",',
                    f'        "{tag}",',
                    f'        "{op}",',
                    "    ),",
                ]
            )
        )
    return blocks


def main() -> None:
    blocks: list[str] = []
    for crate in APP_CRATES + BACKEND_CRATES + OPEN_CRATES:
        manifest = ROOT / "crates" / crate / "src" / "http_route_manifest.rs"
        blocks.extend(extract_http_routes(manifest))

    if not blocks:
        raise SystemExit("no routes extracted for combined manifest")

    output = "\n".join(
        [
            "// @generated by tools/gen_appstore_combined_http_route_manifest.py — do not edit",
            "",
            "use sdkwork_web_core::{HttpMethod, HttpRoute, HttpRouteManifest};",
            "",
            "const HTTP_ROUTES: &[HttpRoute] = &[",
            *blocks,
            "];",
            "",
            "pub fn appstore_route_manifest() -> HttpRouteManifest {",
            "    HttpRouteManifest::new(HTTP_ROUTES)",
            "}",
            "",
            "pub fn appstore_public_path_prefixes() -> Vec<String> {",
            '    vec!["/health".to_owned(), "/healthz".to_owned()]',
            "}",
            "",
            "pub fn appstore_open_api_prefixes() -> Vec<String> {",
            '    vec!["/store/v3/api".to_owned()]',
            "}",
            "",
        ]
    )

    out_path = ROOT / "crates" / "sdkwork-appstore-api-server" / "src" / "http_route_manifest.rs"
    out_path.write_text(output, encoding="utf-8")
    print(f"wrote {len(blocks)} routes to {out_path}")


if __name__ == "__main__":
    main()
