#!/usr/bin/env python3
"""Generate http_route_manifest.rs from appstore route crate routes.rs."""

from __future__ import annotations

import re
import sys
from pathlib import Path

METHOD_MAP = {
    "GET": "Get",
    "POST": "Post",
    "PATCH": "Patch",
    "DELETE": "Delete",
    "PUT": "Put",
}

ROUTE_ENTRY = re.compile(
    r"RouteDefinition\s*\{\s*"
    r'method:\s*"(\w+)",\s*'
    r'path:\s*"([^"]+)",\s*'
    r'operation_id:\s*"([^"]+)",',
    re.MULTILINE,
)


def parse_routes(routes_path: Path) -> list[tuple[str, str, str]]:
    text = routes_path.read_text(encoding="utf-8")
    return ROUTE_ENTRY.findall(text)


def render(
    routes: list[tuple[str, str, str]],
    fn_name: str,
    tag: str,
    auth: str,
) -> str:
    lines = [
        "// @generated by tools/gen_appstore_http_route_manifest.py — do not edit",
        "",
        "use sdkwork_web_core::{HttpMethod, HttpRoute, HttpRouteManifest};",
        "",
        "const HTTP_ROUTES: &[HttpRoute] = &[",
    ]
    for method, path, op in routes:
        hm = METHOD_MAP[method]
        lines.extend(
            [
                f"    HttpRoute::{auth}(",
                f"        HttpMethod::{hm},",
                f'        "{path}",',
                f'        "{tag}",',
                f'        "{op}",',
                "    ),",
            ]
        )
    lines.extend(
        [
            "];",
            "",
            f"pub fn {fn_name}() -> HttpRouteManifest {{",
            "    HttpRouteManifest::new(HTTP_ROUTES)",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) not in (5, 6):
        print(
            "usage: gen_appstore_http_route_manifest.py "
            "<routes.rs> <output.rs> <fn_name> <tag> [dual_token|api_key|public]",
            file=sys.stderr,
        )
        return 1

    routes_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])
    fn_name = sys.argv[3]
    tag = sys.argv[4]
    auth = sys.argv[5] if len(sys.argv) == 6 else "dual_token"

    routes = parse_routes(routes_path)
    if not routes:
        raise SystemExit(f"no RouteDefinition entries found in {routes_path}")

    output_path.write_text(render(routes, fn_name, tag, auth), encoding="utf-8")
    print(f"wrote {len(routes)} routes to {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
